[workspace]
resolver = "2"
members = [
    "stm32-data-gen",
    "stm32-data-serde",
    "stm32-metapac-gen",
    "stm32-data-macros",
]
exclude = [
    "build"
]

[workspace.dependencies]
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "e09c27da1f97d77e73dda25ca9051b60c986b75a" }

# Optimize for dev experience: shortest "build+run" time after making a small change.
[profile.release]
debug = true
incremental = true
panic = 'abort'
opt-level = 2
